// <auto-generated />
using CryptMindCapAPI.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptMindCapAPI.Migrations
{
    [DbContext(typeof(FlagsDbContext))]
    partial class FlagsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CryptMindCapAPI.Core.Data.FeatureOverride", b =>
                {
                    b.Property<string>("EntitlementId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("entitlement_id");

                    b.Property<string>("FlagKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("flag_key");

                    b.Property<bool>("Value")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("value");

                    b.HasKey("EntitlementId", "FlagKey");

                    b.ToTable("overrides", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
